---
title: "MRMS pixel analysis"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

# load packages
library(R.utils) #to unzip the gz files
library(tidyverse)
library(lubridate)
library(raster)
library(rgdal)
library(sf)
library(sp)
library(mapview)
library(terra)
library(tmap)
library(readr)
library(gridExtra)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(here)
library(irr)
library(plotly)
library(kableExtra)
library(dataRetrieval)

```

```{r sensor coords}
# ETF watersheds - don't need right now
et_sheds <- vect('./data/watershed_bnd_UTM.shp') %>%
  terra::project(., 'EPSG:26913')

benn_sheds <- vect('./data/mulch_study_watersheds.shp') %>%
  terra::project(., 'EPSG:26913')

# all rain sensors for CPF, ETF, Bennett
rain <- read_csv('./data/sensor_coords.csv') %>%
  filter(type == 'rain') %>%
  drop_na() %>%
  st_as_sf(coords = c('x', 'y'), crs = 4326) %>%
  st_transform(crs = st_crs(et_sheds))

# bounding box based on rain sensors to crop MRMS data
bbox <- st_bbox(rain)
et_bbox <- st_bbox(et_sheds)

# bounding box cuts off some points, so expand it
xrange <- bbox$xmax - bbox$xmin # range of x values
yrange <- bbox$ymax - bbox$ymin # range of y values

bbox[1] <- bbox[1] - (0.1 * xrange) # xmin - left
bbox[3] <- bbox[3] + (0.1 * xrange) # xmax - right
bbox[2] <- bbox[2] - (0.1 * yrange) # ymin - bottom
bbox[4] <- bbox[4] + (0.1 * yrange) # ymax - top

# double-check it includes all points
#mapview(bbox) + mapview(rain)

```

# TB PIXEL ANAYLSIS

## 2021 

```{r extract tb pixels 2021}

# # unzip all grib2.gz (only do this once) **ALREADY COMPLETE
# zip <- list.files(path = '/Users/megansears/Documents/MRMS/QPE/2021', pattern = '.gz',
#                   full.names = T)
# 
# #unzip all listed files
# unzip <- lapply(zip, gunzip)

setwd('/Users/megansears/Documents/MRMS/MultiSensor/2021')

filenames <- list.files(".", pattern='.grib2', full.names=F)   

  for(fileName in filenames) {

#pull in raster
r <- rast(fileName) %>%
  terra::project(., 'EPSG:26913')

#crop raster to cpf
crop <- terra::crop(r, ext(bbox))

names(crop) <- 'p_mmhr'

#extract using terra bc it has more functions :)
extract <- terra::extract(crop, rain)
extract$name <- rain$site

timestamp <- substr(fileName, 33, 47)

extract <- extract %>%
  mutate(datetime = ymd_hms(timestamp)) %>%
  mutate(datetime = datetime - (7 * 60 * 60)) %>%
  mutate(doy = yday(datetime)) %>%
  mutate(hour = hour(datetime))

write.csv(extract, paste0('extract_', extract$doy[1],'_', extract$hour[1],'.csv'))

  }

```

```{r get pixel csv 2021}

#compile all CSVs
# pixel_21 <- list.files(path='/Users/megansears/Documents/MRMS/etf_pixel_2021', full.names = T) %>%
#   lapply(read_csv) %>%
#   bind_rows
# 
# pixel_22 <- list.files(path='/Users/megansears/Documents/MRMS/etf_pixel_2022', full.names = T) %>%
#   lapply(read_csv) %>%
#   bind_rows
# 
# #remove random columns
# pixel_21 <- pixel_21 %>%
#   dplyr::select(-c(...1, ID))
# 
# pixel_22 <- pixel_22 %>%
#   dplyr::select(-c(...1, ID, doy, hour))
# 
# write_csv(pixel_21, 'mrms_pixel_21.csv')
# write_csv(pixel_22, 'mrms_pixel_22.csv')

```

## 2022

```{r extract tb pixels 2022}

setwd('/Users/megansears/Documents/MRMS/MultiSensor/2022')

filenames <- list.files(".", pattern='.grib2', full.names=F)   

  for(fileName in filenames) {

#pull in raster
r <- rast(fileName) %>%
  terra::project(., 'EPSG:26913')

#crop raster to cpf
crop <- terra::crop(r, ext(bbox))

names(crop) <- 'p_mmhr'

#extract using terra bc it has more functions :)
extract <- terra::extract(crop, rain)
extract$name <- rain$site

timestamp <- substr(fileName, 33, 47)

extract <- extract %>%
  mutate(datetime = ymd_hms(timestamp)) %>%
  mutate(datetime = datetime - (7 * 60 * 60)) %>%
  mutate(doy = yday(datetime)) %>%
  mutate(hour = hour(datetime))

write.csv(extract, paste0('extract_', extract$doy[1],'_', extract$hour[1],'.csv'))

  }

```

```{r get pixel csv 2022}

#compile all CSVs
# pixel_21 <- list.files(path='/Users/megansears/Documents/MRMS/etf_pixel_2021', full.names = T) %>%
#   lapply(read_csv) %>%
#   bind_rows
# 
# pixel_22 <- list.files(path='/Users/megansears/Documents/MRMS/etf_pixel_2022', full.names = T) %>%
#   lapply(read_csv) %>%
#   bind_rows
# 
# #remove random columns
# pixel_21 <- pixel_21 %>%
#   dplyr::select(-c(...1, ID))
# 
# pixel_22 <- pixel_22 %>%
#   dplyr::select(-c(...1, ID, doy, hour))
# 
# write_csv(pixel_21, 'mrms_pixel_21.csv')
# write_csv(pixel_22, 'mrms_pixel_22.csv')

```

# WATERSHED MRMS

## Pull watershed MRMS
Using the multi sensor QPE 

```{r}
# do ET first 
setwd('/Users/megansears/Documents/MRMS/MultiSensor/2022')

filenames <- list.files(".", pattern='.grib2', full.names=F)   

  for(fileName in filenames) {

#pull in raster
r <- rast(fileName) %>%
  terra::project(., 'EPSG:26913')

#crop raster to cpf
crop <- terra::crop(r, ext(bbox))

names(crop) <- 'p_mmhr'

#extract using terra bc it has more functions :)
extract <- terra::extract(crop, et_sheds, fun = mean, touches = T, exact = T)
extract$name <- et_sheds$Name

timestamp <- substr(fileName, 33, 47)

extract <- extract %>%
  mutate(datetime = ymd_hms(timestamp)) %>%
  mutate(datetime = datetime - (7 * 60 * 60)) %>%
  mutate(doy = yday(datetime)) %>%
  mutate(hour = hour(datetime))

write.csv(extract, paste0('extract_', extract$doy[1],'_', extract$hour[1],'.csv'))

  }

```

```{r get watershed csv 2021}

#compile all CSVs
etf_mrms_21 <- list.files(path='/Users/megansears/Documents/MRMS/MultiSensor/etf_2021', full.names = T) %>%
  lapply(read_csv) %>%
  bind_rows

etf_mrms_22 <- list.files(path='/Users/megansears/Documents/MRMS/MultiSensor/etf_2022', full.names = T) %>%
  lapply(read_csv) %>%
  bind_rows

#remove random columns
etf_mrms_21 <- etf_mrms_21 %>%
  dplyr::select(-c(...1, ID))

etf_mrms_22 <- etf_mrms_22 %>%
  dplyr::select(-c(...1, ID, doy, hour))

write_csv(etf_mrms_21, 'etf_mrms_21.csv')
write_csv(etf_mrms_22, 'etf_mrms_22.csv')

```


