---
title: "2-min MRMS event analysis"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r, include = F}

knitr::opts_chunk$set(echo = F,
                      message = F,
                      fig.width = 12,
                      fig.height = 6)

library(tidyverse)
library(stringr)
library(lubridate)
library(plotly)
library(kableExtra)
library(here)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(zoo)
library(corrplot)
library(stats)

```

# Functions
Create as Rdata functions down the line

```{r}

# get events - some initial steps nbeed to happen before
# add into function eventually: filtering less than 0.3 mm out (which also takes care of 0 mm)
get_mrms_events <- function(df, datetime) {
  df$datetime = as.POSIXct(df$datetime,tz="MST", format="%m/%d/%Y %H:%M")
  df$datenumeric=as.numeric(df$datetime)

  for (i in 2:nrow(df)) {
    df[i,'dt']=df[i,'datenumeric']-df[i-1,'datenumeric']
  }
  df$dt_hr=as.numeric(df$dt)/60/60
  
  #start new event if time between rows is  >=6
  df$event=1
  for (i in 2:nrow(df)) {
    df[i,'event']=ifelse(df[i,'dt_hr']<6,df[i-1,'event'],df[i-1,'event']+1)
  }
  return(df)
}
```

# Prep data

```{r rainfall metrics, echo=FALSE}

# load in 2021-2023 data
all_2023 <- read_csv('/Users/megansears/Desktop/debris_flows/2023_p/cpf_debrisflow_p_2023.csv') %>%
  dplyr::select(-1) %>%
  rename(ID = catchment) %>%
  mutate(datetime = force_tz(datetime, tzone = 'MST')) #%>%
  #filter(!ID == 'MiddleUnburned')
  
# load in 2021 and 2022 data
all_2021 <- read_csv('/Users/megansears/Desktop/debris_flows/2021_p/cpf_debrisflow_p_2021.csv') %>%
  dplyr::select(-1) %>%
  mutate(datetime = force_tz(datetime, tzone = 'MST')) #%>%
  #filter(!ID == 'MiddleUnburned')

all_2022 <- read_csv('/Users/megansears/Desktop/debris_flows/2022_p/cpf_debrisflow_p_2022.csv') %>%
  dplyr::select(-1) %>%
  mutate(datetime = force_tz(datetime, tzone = 'MST')) #%>%
  #filter(!ID == 'MiddleUnburned')

# # load in lower ET sites (including mub - delete mub from above dataframes)
# lower_et_2022 <- read_csv('./data/final/mrms/2022_mrms_lowerET.csv') %>%
#   dplyr::select(-1) %>%
#   rename(ID = catchment) %>%
#   mutate(datetime = force_tz(datetime, tzone = 'MST'))
# 
# lower_et_2023 <- read_csv('./data/final/mrms/2023_mrms_lowerET.csv') %>%
#   dplyr::select(-1) %>%
#   rename(ID = catchment) %>%
#   mutate(datetime = force_tz(datetime, tzone = 'MST'))

# bind them 2021 and 2022 together & resample to 10 min
all <- bind_rows(all_2021, 
                 all_2022, 
                 all_2023) #%>%
  # mutate(ID = case_when(
  #     ID == 'Pass 1' ~ 'p1',
  #     ID == 'Pass 2' ~ 'p2',
  #     ID == 'HighUnmulch' ~ 'hum',
  #     ID == 'HighMulch' ~ 'hm',
  #     ID == 'MiddleUnmulch' ~ 'mum',
  #     ID == 'MiddlePartialMulch' ~ 'mpm',
  #     ID == 'MiddleMulch' ~ 'mm_et',
  #     TRUE ~ ID)) %>%
  # bind_rows(.,
  #           lower_et_2023,
  #           lower_et_2022)

# export all as 2 min mrms precip for all sites
write_csv(all, '/Users/megansears/Desktop/debris_flows/cpf_combined_p.csv')

all <- read_csv('/Users/megansears/Desktop/debris_flows/cpf_combined_p.csv')

all <- all %>%
  mutate(year = year(datetime),
         timestamps_10min = ceiling_date(datetime, "10 mins")) %>%
  group_by(ID, timestamps_10min) %>%
  summarize(rain_mm = sum(p_mm)) %>%
  rename(datetime = timestamps_10min)

test <- all %>% filter(ID == 'b1')

```

# Events
Derived from 2-min MRMS data

```{r}

#try for all sites
get_mrms_all_events <- function(all, ID_name) {
  
  events <- all %>%
  filter(ID == 'b4', #update b1 to ID_name
         rain_mm > 0.3) #%>%
  get_mrms_events(., datetime) %>%
  group_by(event) %>%
  mutate(start_time = min(datetime),
         end_time = max(datetime)) %>%
  dplyr::select(-c(datenumeric, dt, dt_hr)) %>%
  complete(datetime = seq(min(datetime), max(datetime), by = "10 mins")) %>%
  arrange(event, datetime) %>%
  fill(start_time, end_time, ID) %>%
  ungroup() %>%
  mutate(rain_mm = ifelse(is.na(rain_mm), 0, rain_mm))
    
  return(events)
}

# list out sites 
sites <- unique(all$ID)

# get events for all sites
all_events <- map(sites, ~ get_mrms_all_events(all, .)) %>%
  bind_rows(.)

```

# Intensity analysis

```{r}

# get 10, 20, 30, 60 min intensities

#start with 1 site
get_mrms_intensities <- function(all_events, ID_name) {

intens <- all_events %>%
  filter(ID == ID_name) %>%
  group_by(event) %>%
  mutate(max10_mm = max(rain_mm),
         sum20_mm = rollapplyr(rain_mm, width = 2, FUN = sum, partial = TRUE),
         max20_mm = max(sum20_mm),
         sum30_mm = rollapplyr(rain_mm, width = 3, FUN = sum, partial = TRUE),
         max30_mm = max(sum30_mm),
         sum60_mm = rollapplyr(rain_mm, width = 6, FUN = sum, partial = TRUE),
         max60_mm = max(sum60_mm),
         event_sum_mm = sum(rain_mm),
         MI10_mmhr = max10_mm*6,
         MI20_mmhr = max20_mm*3,
         MI30_mmhr = max30_mm*2,
         MI60_mmhr = max60_mm) %>%
  dplyr::select(-c(max10_mm, max20_mm, max30_mm, max60_mm,
            sum20_mm, sum30_mm, sum60_mm, datetime,
            rain_mm)) %>%
  ungroup() %>%
  distinct(start_time, .keep_all = T) %>%
  mutate(duration_hr = difftime(end_time, start_time, unit = 'hour')) %>%
  filter(event_sum_mm > 1)
  
}

sites <- unique(all$ID)

# get events for all sites
all_intens <- map(sites, ~ get_mrms_intensities(all_events, .)) %>%
  bind_rows(.)

all_intens <- all_intens %>%
  group_by(ID) %>%
  arrange(event) %>%
  mutate(event = 1:n()) %>%
  mutate(year = year(start_time))

#ggplot(test, aes(y=MI60_mmhr, x=ID)) + geom_boxplot()
#ggplot(test, aes(y=event_sum_mm, x=ID)) + geom_boxplot()

write.csv(all_intens, './data/final/mrms/all_mrms_intensities.csv')

```

