---
title: "Catchment variables - figures"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r, include = F}

knitr::opts_chunk$set(echo = F,
                      message = F,
                      fig.width = 12,
                      fig.height = 6)

library(tidyverse)
library(plotly)
library(ggplot2); theme_set(theme_bw(base_size = 14))
library(cowplot)

```

# Catchment variables

```{r}

inputs <- read_csv('./data/final_model_inputs/inputs_combine.csv')

# create snow persistence categories
inputs <- inputs %>% 
  mutate(sp_cat = if_else(SP_mean > 60,
                          'Seasonal',
                          'Intermittent'))

# remove the unburned sites from inputs for dnbr and ndvi
inputs_edit <- inputs %>%
  mutate(mean_dnbr = if_else(site %in% c('bighorn',
                                         'michigan',
                                         'p1'),
                             NA,
                             mean_dnbr),
         NDVI_2021.x = if_else(site %in% c('bighorn',
                                           'michigan',
                                           'p1'),
                               NA,
                               NDVI_2021.x),
         NDVI_2022.x = if_else(site %in% c('bighorn',
                                           'michigan',
                                           'p1'),
                               NA,
                               NDVI_2022.x),
         NDVI_2023.x = if_else(site %in% c('bighorn',
                                           'michigan',
                                           'p1'),
                               NA,
                               NDVI_2023.x))

# make df long & remove the categorical geology
inputs_long <- inputs_edit %>%
  select(-c(site, geo_general.x, geology.x)) %>%
  pivot_longer(!c(fire, sp_cat), 
               names_to = 'vars',
               values_to = 'vals')


```

# Soil

```{r}

# for actual figure - select soils & geo, shape, burn & veg
vars <- inputs_long %>%
  filter(vars %in% c('AVG_CLAY',
                     'AVG_KSAT',
                     'aws0150wta')) %>%
    mutate(vars = case_match(vars,
    "AVG_CLAY" ~ "% clay",
    "AVG_KSAT" ~ "Ksat",
    "aws0150wta" ~ "Avail. water storage")) %>%
  mutate(fire = if_else(fire == 'cpf',
                        'CPF',
                        'ETF'))

# values for results
vars_summary <- vars %>%
  group_by(vars, fire, sp_cat) %>%
  summarize(
    mean_val = mean(vals, na.rm = TRUE),
    sd_val = sd(vals, na.rm = TRUE))

vars_fire <- vars %>%
  group_by(vars, fire) %>%
  summarize(mean = mean(vals))
  
soil <- ggplot(vars, aes(x=fire, 
                 y=vals,
                 fill=sp_cat)) + 
  geom_boxplot(           
  color = "black",
    size = 0.2,                 
    width = 0.6) +
  scale_fill_manual(values = c('#7570B3', "#D95F02")) +
  labs(x = NULL,
    y = NULL,
    fill = 'Snow persistence') +
  theme(panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.position = "bottom",
    plot.margin = ggplot2::margin(t = 20, r = 5, b = 5, l = 5)) +
  facet_wrap(~vars, scales='free_y', ncol=3) 

soil

ggsave(
  '/Users/megansears/Documents/Repos/post-fire_rainfall/figures/SR_response/soil_boxplot.png',
       dpi=600,
       width=12,
       height=12)

```

# Terrain morphology

```{r}

# for actual figure - select soils & geo, shape, burn & veg
vars <- inputs_long %>%
  filter(vars %in% c('ELONGATION.x',
                     'flow_length_m',
                     'frac_valley',
                     'hypso75',
                     'slope30_frac')) %>%
    mutate(vars = case_match(vars,
    "ELONGATION.x" ~ "Elongation",
    "flow_length_m" ~ "Max flow path",
    "frac_valley" ~ "Valleys and hollows",
    "hypso75" ~ "Area > 75% elevation",
    "slope30_frac" ~ "Slopes > 30")) %>%
  mutate(fire = if_else(fire == 'cpf',
                        'CPF',
                        'ETF'))

# values for results
vars_summary <- vars %>%
  group_by(vars, fire, sp_cat) %>%
  summarize(
    mean_val = mean(vals, na.rm = TRUE),
    sd_val = sd(vals, na.rm = TRUE))

vars_fire <- vars %>%
  group_by(vars, fire) %>%
  summarize(mean = mean(vals))

terrain_plot <- ggplot(vars, aes(x=fire, 
                 y=vals,
                 fill=sp_cat)) + 
  geom_boxplot(           
  color = "black",
    size = 0.2,                 
    width = 0.6) +
  scale_fill_manual(values = c('#7570B3', "#D95F02")) +
  labs(x = NULL,
    y = NULL,
    fill = 'Snow persistence') +
  theme(panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.position = "bottom",
    plot.margin = ggplot2::margin(t = 20, r = 5, b = 5, l = 5)) +
  facet_wrap(~vars, scales='free_y', ncol=3) 

terrain_plot

ggsave(
  '/Users/megansears/Documents/Repos/post-fire_rainfall/figures/SR_response/terrainmorph_boxplot.png',
       dpi=600,
       width=12,
       height=12)


```

# Vegetation and burn severity

```{r}

vars <- inputs_long %>%
  filter(vars %in% c('mean_dnbr',
                     'NDVI_2021.x',
                     'NDVI_2022.x',
                     'NDVI_2023.x')) %>%
    mutate(vars = case_match(vars,
    "mean_dnbr" ~ "Mean dNBR",
    "NDVI_2021.x" ~ "NDVI 2021",
    "NDVI_2022.x" ~ "NDVI 2022",
    "NDVI_2023.x" ~ "NDVI 2023")) %>%
  mutate(fire = if_else(fire == 'cpf',
                        'CPF',
                        'ETF'))

# values for results
vars_summary <- vars %>%
  group_by(vars, fire, sp_cat) %>%
  summarize(
    mean_val = mean(vals, na.rm = TRUE),
    sd_val = sd(vals, na.rm = TRUE))

vars_fire <- vars %>%
  group_by(vars, fire) %>%
  summarize(mean = mean(vals, na.rm=T))

ndvi <- vars %>%
  filter(!vars == 'Mean dNBR') %>%
  mutate(
    year = case_when(
      str_detect(vars, "NDVI 2021") ~ 2021,
      str_detect(vars, "NDVI 2022") ~ 2022,
      str_detect(vars, "NDVI 2023") ~ 2023),
    variable = case_when(
      str_detect(vars, "NDVI") ~ "NDVI"))

ndvi <- ndvi %>%
  mutate(group = paste(fire, year, sep = " "))


ndvi_plot <- ggplot(ndvi, aes(x = group, 
                 y = vals,
                 fill = sp_cat)) + 
  geom_boxplot(
    color = "black",
    size = 0.2,                 
    width = 0.6
  ) +
  scale_fill_manual(values = c('#7570B3', "#D95F02")) +
  labs(x = NULL,
       y = NULL,
       fill = 'Snow persistence') +
  ggtitle("NDVI") +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        strip.background = element_blank(),
        text = element_text(color = "black"),
        axis.title = element_text(color = "black"),
        axis.text.x = element_text(color = "black"),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, size = 14))

ndvi_plot

burn_plot <- vars %>%
  filter(vars == 'Mean dNBR') %>%
  ggplot(., aes(x=fire, 
                 y=vals,
                 fill=sp_cat)) + 
  geom_boxplot(           
  color = "black",
    size = 0.2,                 
    width = 0.6) +
  ggtitle('Mean dNBR') +
  scale_fill_manual(values = c('#7570B3', "#D95F02")) +
  labs(x = NULL,
    y = NULL,
    fill = 'Snow zone') +
  theme(panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, size = 14),
    plot.margin = ggplot2::margin(t = 20, r = 5, b = 5, l = 5))

burn_plot  

legend <- cowplot::get_plot_component(burn_plot, "guide-box", return_all = TRUE)[[3]]

# Step 2: Remove legends from both plots
burn_plot_noleg <- burn_plot + theme(legend.position = "none")
ndvi_plot_noleg <- ndvi_plot + theme(legend.position = "none")

# Step 3: Combine the plots without the legends
burn_veg <- plot_grid(
  burn_plot_noleg,
  ndvi_plot_noleg,
  ncol = 2,  # Adjust the number of columns as needed
  align = "hv",  # Better alignment
  axis = "tblr"  # Align all axis directions
)

burn_veg

```

# Combine

```{r}

# Step 2: Remove legends from individual plots
soil_noleg <- soil + theme(legend.position = "none")
terrain_noleg <- terrain_plot + theme(legend.position = "none")



soil_terrain <- plot_grid(
  soil_noleg, terrain_noleg,
  labels = c("a) Soil", "b) Terrain"),
  label_size = 14)

soil_terrain

plot_grid(soil_terrain, burn_veg, legend, ncol=1)

burn_veg_labeled <- plot_grid(
  burn_veg,
  labels = "c) Vegetation",
  label_size = 14
)

# Then combine everything
final_plot <- plot_grid(
  soil_terrain,       # Your first plot (no label)
  burn_veg_labeled,   # burn_veg with label
  legend,             # The extracted legend
  ncol = 1,
  rel_heights = c(1, 1, 0.05)
)

final_plot

ggsave(
  '/Users/megansears/Documents/Repos/post-fire_rainfall/figures/SR_response/var_cats_boxplot.png',
       dpi=600,
       width=12,
       height=8)

```

