---
title: "Exploratory mediation"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r, include = F}

library(pacman)

p_load(here, 
       regsem, 
       semPlot, 
       caret, 
       ggh4x, 
       ggdag, 
       tidyverse, 
       ggsankeyfier, 
       reshape, 
       networkD3, 
       igraph, 
       ggraph, 
       ggridges,
       glmnet,
       ggcorrplot)

```

# Prep

```{r}

response <- read_csv('./data/final_model_inputs/events_inputs.csv') %>%
  select(site,
         sp_cat, # categorical
         fire, # categorical
         stage_rise_cm,
         lag2peak_halfP,
         lag2peak_Pstart,
         MI60_mmhr,
         lag_pwd,
         terrain_hypso75 = hypso75,
         terrain_hypso25 = hypso25,
         terrain_hypso50 = hypso50,
         terrain_connec = IC,
         terrain_conn_dnbr = hydraulic_func_conn,
         area_km2 = area_km2.x,
         terrain_rc_circle = RC_CIRCLE.x,
         terrain_slope40 = slope40_frac,
         soil_brockdepmin = brockdepmin,
         terrain_recharge = frac_recharge_area,
         terrain_vbw = avg_vbw_m,
         soil_sand = AVG_SAND,
         mean_dnbr, 
         soil_clay = AVG_CLAY,
         soil_ksat = AVG_KSAT, 
         terrain_elongation = ELONGATION.x, 
         soil_availwaterstor = aws0150wta, 
         NDVI, 
         terrain_vall_holl = frac_valley,
         terrain_flowlength = flow_length_m, 
         terrain_slope30 = slope30_frac, 
         SP_mean,
         terrain_hypsoint = hypso_integral,
         year,
         terrain_glacial = frac_glacial,
         fire_no) %>%
  mutate(site_number = as.integer(factor(site))) %>% # give each site a number
  select(-site)


```

# Correlations

```{r}

corr_prep <- response %>%
  select(-c(MI60_mmhr, 
            #lag_pwd,
            lag2peak_halfP,
            lag2peak_Pstart,
            stage_rise_cm,
            fire_no)) %>%
  select(where(is.numeric))

corr_matrix <- cor(corr_prep, use = "complete.obs")

ggcorrplot(corr_matrix, method = "square", 
           hc.order = FALSE,
           type = "lower", 
           lab = TRUE, 
           lab_col = "black", 
           lab_size = 3, 
           colors = c("blue", "white", "red")) +
  theme(
    plot.margin = margin(1, 1,1,1),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(hjust = 1))


masked_corr <- corr_matrix
masked_corr[abs(masked_corr) < 0.7] <- NA

ggcorrplot(masked_corr, method = "square", 
           #hc.order = FALSE,
           type = "lower", 
           lab = TRUE, 
           lab_col = "black", 
           lab_size = 3, 
           colors = c("blue", "white", "red")) +
  theme(
    plot.margin = margin(1, 1,1,1),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(hjust = 1))

```


# Exploratory mediation

## No bootstrapping yet

### Stage rise

```{r}

data <- response %>%
  filter(fire == 'cpf',
         sp_cat == 'low') %>%
  drop_na()

mediators <- c(
  "hypso75", 
  "hypso25", 
  "hypso50",
  "hypso_integral", 
  "IC", 
  "hydraulic_func_conn",
  "area_km2", 
  "rc_circle",
  "elongation",
  "slope40_frac",
  "slope30_frac",
  "avg_vbw_m", 
  "frac_recharge_area",
  "frac_valley", 
  "flow_length_m",
  "frac_glacial",
  "brockdepmin", 
  "AVG_SAND", 
  "AVG_CLAY", 
  "AVG_SILT", 
  "AVG_KSAT",
  "aws0150wta", 
  "mean_dnbr", 
  "SP_mean",
  "geo_coded"
)

dv <- 'stage_rise_cm'

iv <- c('MI60_mmhr',
        'lag_pwd')
        
covariates <- c('site_number',
                'year',
                'NDVI')

# run 
result <- xmed(data = data, 
               iv = iv, 
               dv = dv, 
               mediators = mediators,
               covariates = covariates,
               nfolds = 10, 
               type = 'ridge')

ivs <- names(result)[names(result) %in% c(
  'MI60_mmhr',
  'lag_pwd'
)]
    
# Combine all paths into a single tidy data frame for each resample
effect_df <- map_dfr(ivs, function(iv_name) {
      a <- result[[iv_name]]$a.coefs
      b <- result[[iv_name]]$b.coefs
      indirect <- as.numeric(result[[iv_name]]$indirect)
      mediator_names <- names(a)
      
      tibble(
        IV = iv_name,
        Mediator = mediator_names,
        a_coef = a,
        b_coef = b[mediator_names],
        weight = indirect
      )
    })
    
effect_df <- effect_df %>%
      mutate(effects = 'coefIndir') %>%
      mutate(depVar = dv)

 # make weight fill by white if 0 but keep other colors 
 effect_df_plot <- effect_df %>%
  mutate(weight_for_plot = ifelse(weight == 0, NA, weight))

ggplot(effect_df_plot, 
       aes(x = b_coef, y = Mediator)) + 
  theme_bw(base_size = 20) +
  geom_point(aes(fill = weight_for_plot,
                 color = weight_for_plot), 
             shape = 21, 
             size = 6, 
             stroke = 0.5,  # optional: makes the outline more visible
             color = 'gray50') + 
  facet_wrap(~IV) +
  labs(x = 'Direct effect size\nMediator -> DV',
       fill = 'Indirect effect size', 
       color = 'Indirect effect size') +
  paletteer::scale_color_paletteer_c("grDevices::RdYlBu", na.value = "white") +
  paletteer::scale_fill_paletteer_c("grDevices::RdYlBu", na.value = "white") +
  ggtitle('Stage rise - ALL')

# plot
 # ggplot(effect_df, 
 #        aes(x = b_coef, y = Mediator)) + 
 #   theme_bw(base_size = 20) +
 #  geom_point(aes(fill = weight,
 #                 color = weight), 
 #             shape = 21, 
 #             size = 6, 
 #             color = 'gray50') + 
 #   facet_wrap(~IV) +
 #  labs(x = 'Direct effect size\nMediator -> DV',
 #       fill = 'Indirect effect size', 
 #       color = 'Indirect effect sizer') +
 #  paletteer::scale_color_paletteer_c("grDevices::RdYlBu") +
 #  paletteer::scale_fill_paletteer_c("grDevices::RdYlBu") +
 #   ggtitle('Stage rise - CPF intermittent')

```


## Adding bootstrapping

### Stage rise

```{r}

data <- response %>%
  #filter(fire == 'cpf') %>%
  #filter(sp_cat == 'high') %>%
  drop_na()

xmedFunc <- function(dv, n_bootstrap = 200){

  mediators <- c(
  # "terrain_hypso75", 
  # "terrain_connec", 
  # "terrain_elongation",
  # "terrain_slope30",
  # "terrain_vbw", 
  # "terrain_recharge",
  # "terrain_vall_holl", 
  # "terrain_flowlength",
  # "terrain_glacial",
   "soil_clay", 
  # "soil_ksat",
  # "soil_availwaterstor", 
  # "mean_dnbr", 
  # "SP_mean",
    "lag_pwd"
   # "NDVI"
)
  
dv <- 'stage_rise_cm'

iv <- c('MI60_mmhr')
       # 'lag_pwd')
        
covariates <- c('site_number',
                'year')
  
  # Function to apply xmed to a single resampled dataset
  bootstrap_run <- function(data) {
    
    result <- xmed(data = data, 
               iv = iv, 
               dv = dv, 
               mediators = mediators,
               covariates = covariates,
               nfolds = 10, 
               type = 'enet')
    
    ivs <- names(result)[names(result) %in% c('MI60_mmhr')]
                                              # 'lag_pwd')]
    
    # Combine all paths into a single tidy data frame for each resample
    effect_df <- map_dfr(ivs, function(iv_name) {
      
      a <- result[[iv_name]]$a.coefs
      b <- result[[iv_name]]$b.coefs
      indirect <- as.numeric(result[[iv_name]]$indirect)
      mediator_names <- names(a)
      
      tibble(
        IV = iv_name,
        Mediator = mediator_names,
        a_coef = a,
        b_coef = b[mediator_names],
        weight = indirect)
    }) %>%
      mutate(effects = 'coefIndir') %>%
      mutate(depVar = dv)
    
    return(effect_df)
  }
  
  # Bootstrapping: Resample the data and apply the bootstrap_run function
  set.seed(123)  # For reproducibility
  
  bootstrap_results <- map_dfr(1:n_bootstrap, function(i) {
    
    # Resample with replacement
    resampled_data <- data[sample(nrow(data), replace = TRUE), ]
    bootstrap_run(resampled_data)
  })
  
  # Summarize the bootstrap results (e.g., by calculating means and confidence intervals)
  summary_results <- bootstrap_results %>%
    mutate(a_coef = ifelse(a_coef == 0, NA, a_coef),
           b_coef = ifelse(b_coef == 0, NA, b_coef),
           weight = ifelse(weight == 0, NA, weight)) %>%
    group_by(IV, Mediator) %>%
    summarise(
      mean_a_coef = mean(a_coef, na.rm = T),
      mean_b_coef = mean(b_coef, na.rm = T),
      mean_weight = mean(weight, na.rm = T),
      lower_ci_a_coef = quantile(a_coef, 0.025, na.rm = T),
      upper_ci_a_coef = quantile(a_coef, 0.975, na.rm = T),
      lower_ci_b_coef = quantile(b_coef, 0.025, na.rm = T),
      upper_ci_b_coef = quantile(b_coef, 0.975, na.rm = T),
      lower_ci_weight = quantile(weight, 0.025, na.rm = T),
      upper_ci_weight = quantile(weight, 0.975, na.rm = T)
    ) %>%
    mutate(depVar = dv,
           significant = ifelse(lower_ci_weight < 0 &
                                  upper_ci_weight > 0 |
                                  lower_ci_weight > 0 &
                                  upper_ci_weight < 0,
                                "Not", "Sig"))
  
    return(list(
    summary = summary_results,
    bootstrap = bootstrap_results
  ))
}


nb = 200
xmedOut <- xmedFunc('stage_rise_cm', n_bootstrap = nb)

full <- xmedOut$bootstrap
summary <- xmedOut$summary

# write_csv(full,
#           './data/final/exploratory_mediation/stagerise_bs1000_enet_full_low.csv')
# 
# write_csv(summary,
#           './data/final/exploratory_mediation/stagerise_bs1000_enet_summary_low.csv')

summary %>%
  subset(significant == 'Sig') %>%
  ggplot(., aes(x = mean_weight, y = Mediator)) + theme_bw(base_size = 20) +
  geom_vline(xintercept = 0, linetype = 'dashed') +
  geom_linerange(aes(xmin = lower_ci_weight, xmax = upper_ci_weight, y = Mediator), #, fill = mean_a_coef, color = mean_a_coef),
                 size = 1, color = 'gray50') + 
  geom_point(aes(fill = mean_b_coef, color = mean_b_coef), 
             shape = 21, size = 6, color = 'gray50') + 
  facet_wrap(~IV) +
  #xlim(c(-.36, .36)) +
  labs(x = 'Indirect effect size', 
       fill = 'Direct effect size\nMediator -> DV', 
       color = 'Direct effect size\nMediator -> DV') +
  paletteer::scale_color_paletteer_c("grDevices::RdYlBu") +
  paletteer::scale_fill_paletteer_c("grDevices::RdYlBu") 
  #scale_size_continuous(range = c(1,8))
  
# look at all 3: a coef, b coef, weight
long_summary <- summary %>%
  select(IV, Mediator, starts_with("mean_"), starts_with("lower_ci_"), starts_with("upper_ci_"), depVar) %>%
  pivot_longer(
    cols = c(mean_a_coef, mean_b_coef, mean_weight),
    names_to = "effect_type",
    names_prefix = "mean_",
    values_to = "estimate"
  ) %>%
  mutate(
    lower_ci = case_when(
      effect_type == "a_coef" ~ lower_ci_a_coef,
      effect_type == "b_coef" ~ lower_ci_b_coef,
      effect_type == "weight" ~ lower_ci_weight
    ),
    upper_ci = case_when(
      effect_type == "a_coef" ~ upper_ci_a_coef,
      effect_type == "b_coef" ~ upper_ci_b_coef,
      effect_type == "weight" ~ upper_ci_weight
    )
  )

# long_summary %>%
#   filter(IV == 'lag_pwd') %>% 
#   filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
# ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
#   geom_vline(xintercept = 0, color = "black") +
#   geom_point(aes(color = effect_type), size = 3) +
#   geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
#   facet_wrap(~effect_type, scales = "free_x") +
#   labs(
#     x = "Effect Size with 95% CI",
#     y = "Mediator",
#     title = "Stage rise, lag PWD, low SZ",
#     color = "Effect Type"
#   ) +
#   theme_bw(base_size = 14)

long_summary %>%
  filter(IV == 'MI60_mmhr') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "Stage rise, MI60, all",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)




```


### Lag to peak

```{r}

data <- response %>%
  #filter(fire == 'etf') %>%
  #filter(sp_cat == 'high') %>%
  drop_na()

xmedFunc <- function(dv, n_bootstrap = 1000){
  #n_bootstrap = 10

   mediators <- c(
  "terrain_hypso75", 
  "terrain_connec", 
  "terrain_elongation",
  "terrain_slope30",
  "terrain_vbw", 
  "terrain_recharge",
  "terrain_vall_holl", 
  "terrain_flowlength",
  "terrain_glacial",
  "soil_clay", 
  "soil_ksat",
  "soil_availwaterstor", 
  "mean_dnbr", 
  "SP_mean"
)
  
dv <- 'lag2peak_halfP'

iv <- c('MI60_mmhr',
        'lag_pwd')
        
covariates <- c('site_number',
                'year',
                'NDVI')
  
  # Function to apply xmed to a single resampled dataset
  bootstrap_run <- function(data) {
    
    result <- xmed(data = data, 
               iv = iv, 
               dv = dv, 
               mediators = mediators,
               covariates = covariates,
               nfolds = 10, 
               type = 'enet')
    
    ivs <- names(result)[names(result) %in% c('MI60_mmhr',
                                              'lag_pwd')]
    
    # Combine all paths into a single tidy data frame for each resample
    effect_df <- map_dfr(ivs, function(iv_name) {
      
      a <- result[[iv_name]]$a.coefs
      b <- result[[iv_name]]$b.coefs
      indirect <- as.numeric(result[[iv_name]]$indirect)
      mediator_names <- names(a)
      
      tibble(
        IV = iv_name,
        Mediator = mediator_names,
        a_coef = a,
        b_coef = b[mediator_names],
        weight = indirect)
    }) %>%
      mutate(effects = 'coefIndir') %>%
      mutate(depVar = dv)
    
    return(effect_df)
  }
  
  # Bootstrapping: Resample the data and apply the bootstrap_run function
  set.seed(123)  # For reproducibility
  
  bootstrap_results <- map_dfr(1:n_bootstrap, function(i) {
    
    # Resample with replacement
    resampled_data <- data[sample(nrow(data), replace = TRUE), ]
    bootstrap_run(resampled_data)
  })
  
  # Summarize the bootstrap results (e.g., by calculating means and confidence intervals)
  summary_results <- bootstrap_results %>%
    mutate(a_coef = ifelse(a_coef == 0, NA, a_coef),
           b_coef = ifelse(b_coef == 0, NA, b_coef),
           weight = ifelse(weight == 0, NA, weight)) %>%
    group_by(IV, Mediator) %>%
    summarise(
      mean_a_coef = mean(a_coef, na.rm = T),
      mean_b_coef = mean(b_coef, na.rm = T),
      mean_weight = mean(weight, na.rm = T),
      lower_ci_a_coef = quantile(a_coef, 0.025, na.rm = T),
      upper_ci_a_coef = quantile(a_coef, 0.975, na.rm = T),
      lower_ci_b_coef = quantile(b_coef, 0.025, na.rm = T),
      upper_ci_b_coef = quantile(b_coef, 0.975, na.rm = T),
      lower_ci_weight = quantile(weight, 0.025, na.rm = T),
      upper_ci_weight = quantile(weight, 0.975, na.rm = T)
    ) %>%
    mutate(depVar = dv,
           significant = ifelse(lower_ci_weight < 0 & 
                                  upper_ci_weight > 0 | 
                                  lower_ci_weight > 0 & 
                                  upper_ci_weight < 0, 
                                "Not", "Sig"))
  
  return(summary_results)
}

nb = 1000
xmedOut <- xmedFunc('lag2peak_halfP', n_bootstrap = nb)

xmedOut %>%
  subset(significant == 'Sig') %>%
  ggplot(., aes(x = mean_weight, y = Mediator)) + theme_bw(base_size = 20) +
  geom_vline(xintercept = 0, linetype = 'dashed') +
  geom_linerange(aes(xmin = lower_ci_weight, xmax = upper_ci_weight, y = Mediator), #, fill = mean_a_coef, color = mean_a_coef),
                 size = 1, color = 'gray50') + 
  geom_point(aes(fill = mean_b_coef, color = mean_b_coef), 
             shape = 21, size = 6, color = 'gray50') + 
  facet_wrap(~IV) +
  #xlim(c(-.36, .36)) +
  labs(x = 'Indirect effect size', 
       fill = 'Direct effect size\nMediator -> DV', 
       color = 'Direct effect size\nMediator -> DV') +
  paletteer::scale_color_paletteer_c("grDevices::RdYlBu") +
  paletteer::scale_fill_paletteer_c("grDevices::RdYlBu") 
  #scale_size_continuous(range = c(1,8))
  
# look at all 3: a coef, b coef, weight
long_summary <- xmedOut %>%
  select(IV, Mediator, starts_with("mean_"), starts_with("lower_ci_"), starts_with("upper_ci_"), depVar) %>%
  pivot_longer(
    cols = c(mean_a_coef, mean_b_coef, mean_weight),
    names_to = "effect_type",
    names_prefix = "mean_",
    values_to = "estimate"
  ) %>%
  mutate(
    lower_ci = case_when(
      effect_type == "a_coef" ~ lower_ci_a_coef,
      effect_type == "b_coef" ~ lower_ci_b_coef,
      effect_type == "weight" ~ lower_ci_weight
    ),
    upper_ci = case_when(
      effect_type == "a_coef" ~ upper_ci_a_coef,
      effect_type == "b_coef" ~ upper_ci_b_coef,
      effect_type == "weight" ~ upper_ci_weight
    )
  )

long_summary %>%
  filter(IV == 'lag_pwd') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "Lag to peak, lag PWD, all sites",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)

long_summary %>%
  filter(IV == 'MI60_mmhr') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "Lag to peak, MI60, all sites",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)

write_csv(long_summary,
          './data/final/exploratory_mediation/lag2peak_bs1000_enet_allsites.csv')

```

# NDVI

## Stage rise

```{r}

data <- response %>%
  filter(year == 2023) %>% 
  #filter(fire == 'etf') %>%
  #filter(sp_cat == 'high') %>%
  drop_na()

xmedFunc <- function(dv, n_bootstrap = 10){
  n_bootstrap = 10

  mediators <- c(
  "hypso75", 
  "hypso25", 
  "hypso50",
  "hypso_integral", 
  "IC", 
  "hydraulic_func_conn",
  "area_km2", 
  "rc_circle",
  "elongation",
  "slope40_frac",
  "slope30_frac",
  "avg_vbw_m", 
  "frac_recharge_area",
  "frac_valley", 
  "flow_length_m",
  "frac_glacial",
  "brockdepmin", 
  "AVG_SAND", 
  "AVG_CLAY", 
  #"AVG_SILT", 
  "AVG_KSAT",
  "aws0150wta", 
  "mean_dnbr", 
  "SP_mean",
  "fire_no",
  "NDVI"
)
  
dv <- 'stage_rise_cm'

iv <- c('MI60_mmhr',
        'lag_pwd')
        
covariates <- c('site_number')
  
  # Function to apply xmed to a single resampled dataset
  bootstrap_run <- function(data) {
    
    result <- xmed(data = data, 
               iv = iv, 
               dv = dv, 
               mediators = mediators,
               covariates = covariates,
               nfolds = 10, 
               type = 'ridge')
    
    ivs <- names(result)[names(result) %in% c('MI60_mmhr',
                                              'lag_pwd')]
    
    # Combine all paths into a single tidy data frame for each resample
    effect_df <- map_dfr(ivs, function(iv_name) {
      
      a <- result[[iv_name]]$a.coefs
      b <- result[[iv_name]]$b.coefs
      indirect <- as.numeric(result[[iv_name]]$indirect)
      mediator_names <- names(a)
      
      tibble(
        IV = iv_name,
        Mediator = mediator_names,
        a_coef = a,
        b_coef = b[mediator_names],
        weight = indirect)
    }) %>%
      mutate(effects = 'coefIndir') %>%
      mutate(depVar = dv)
    
    return(effect_df)
  }
  
  # Bootstrapping: Resample the data and apply the bootstrap_run function
  set.seed(123)  # For reproducibility
  
  bootstrap_results <- map_dfr(1:n_bootstrap, function(i) {
    
    # Resample with replacement
    resampled_data <- data[sample(nrow(data), replace = TRUE), ]
    bootstrap_run(resampled_data)
  })
  
  # Summarize the bootstrap results (e.g., by calculating means and confidence intervals)
  summary_results <- bootstrap_results %>%
    mutate(a_coef = ifelse(a_coef == 0, NA, a_coef),
           b_coef = ifelse(b_coef == 0, NA, b_coef),
           weight = ifelse(weight == 0, NA, weight)) %>%
    group_by(IV, Mediator) %>%
    summarise(
      mean_a_coef = mean(a_coef, na.rm = T),
      mean_b_coef = mean(b_coef, na.rm = T),
      mean_weight = mean(weight, na.rm = T),
      lower_ci_a_coef = quantile(a_coef, 0.025, na.rm = T),
      upper_ci_a_coef = quantile(a_coef, 0.975, na.rm = T),
      lower_ci_b_coef = quantile(b_coef, 0.025, na.rm = T),
      upper_ci_b_coef = quantile(b_coef, 0.975, na.rm = T),
      lower_ci_weight = quantile(weight, 0.025, na.rm = T),
      upper_ci_weight = quantile(weight, 0.975, na.rm = T)
    ) %>%
    mutate(depVar = dv,
           significant = ifelse(lower_ci_weight < 0 & 
                                  upper_ci_weight > 0 | 
                                  lower_ci_weight > 0 & 
                                  upper_ci_weight < 0, 
                                "Not", "Sig"))
  
  return(summary_results)
}

nb = 50
xmedOut <- xmedFunc('stage_rise_cm', n_bootstrap = nb)

xmedOut %>%
  subset(significant == 'Sig') %>%
  ggplot(., aes(x = mean_weight, y = Mediator)) + theme_bw(base_size = 20) +
  geom_vline(xintercept = 0, linetype = 'dashed') +
  geom_linerange(aes(xmin = lower_ci_weight, xmax = upper_ci_weight, y = Mediator), #, fill = mean_a_coef, color = mean_a_coef),
                 size = 1, color = 'gray50') + 
  geom_point(aes(fill = mean_b_coef, color = mean_b_coef), 
             shape = 21, size = 6, color = 'gray50') + 
  facet_wrap(~IV) +
  #xlim(c(-.36, .36)) +
  labs(x = 'Indirect effect size', 
       fill = 'Direct effect size\nMediator -> DV', 
       color = 'Direct effect size\nMediator -> DV') +
  paletteer::scale_color_paletteer_c("grDevices::RdYlBu") +
  paletteer::scale_fill_paletteer_c("grDevices::RdYlBu") 
  #scale_size_continuous(range = c(1,8))
  
# look at all 3: a coef, b coef, weight
long_summary <- xmedOut %>%
  select(IV, Mediator, starts_with("mean_"), starts_with("lower_ci_"), starts_with("upper_ci_"), depVar) %>%
  pivot_longer(
    cols = c(mean_a_coef, mean_b_coef, mean_weight),
    names_to = "effect_type",
    names_prefix = "mean_",
    values_to = "estimate"
  ) %>%
  mutate(
    lower_ci = case_when(
      effect_type == "a_coef" ~ lower_ci_a_coef,
      effect_type == "b_coef" ~ lower_ci_b_coef,
      effect_type == "weight" ~ lower_ci_weight
    ),
    upper_ci = case_when(
      effect_type == "a_coef" ~ upper_ci_a_coef,
      effect_type == "b_coef" ~ upper_ci_b_coef,
      effect_type == "weight" ~ upper_ci_weight
    )
  )

long_summary %>%
  filter(IV == 'lag_pwd') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "2023 Stage rise, lag PWD, all",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)

long_summary %>%
  filter(IV == 'MI60_mmhr') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "2023 Stage rise, MI60, all",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)

write_csv(long_summary,
          './data/final/exploratory_mediation/stagerise2023_bs_ridge_all.csv')
```

## Lag to peak

```{r}

data <- response %>%
  filter(year == 2023) %>% 
  #filter(fire == 'etf') %>%
  #filter(sp_cat == 'high') %>%
  drop_na()

xmedFunc <- function(dv, n_bootstrap = 10){
  n_bootstrap = 10

  mediators <- c(
  "hypso75", 
  "hypso25", 
  "hypso50",
  "hypso_integral", 
  "IC", 
  "hydraulic_func_conn",
  "area_km2", 
  "rc_circle",
  "elongation",
  "slope40_frac",
  "slope30_frac",
  "avg_vbw_m", 
  "frac_recharge_area",
  "frac_valley", 
  "flow_length_m",
  "frac_glacial",
  "brockdepmin", 
  "AVG_SAND", 
  "AVG_CLAY", 
  #"AVG_SILT", 
  "AVG_KSAT",
  "aws0150wta", 
  "mean_dnbr", 
  "SP_mean",
  "fire_no",
  "NDVI"
)
  
dv <- 'lag2peak_halfP'

iv <- c('MI60_mmhr',
        'lag_pwd')
        
covariates <- c('site_number')
  
  # Function to apply xmed to a single resampled dataset
  bootstrap_run <- function(data) {
    
    result <- xmed(data = data, 
               iv = iv, 
               dv = dv, 
               mediators = mediators,
               covariates = covariates,
               nfolds = 10, 
               type = 'ridge')
    
    ivs <- names(result)[names(result) %in% c('MI60_mmhr',
                                              'lag_pwd')]
    
    # Combine all paths into a single tidy data frame for each resample
    effect_df <- map_dfr(ivs, function(iv_name) {
      
      a <- result[[iv_name]]$a.coefs
      b <- result[[iv_name]]$b.coefs
      indirect <- as.numeric(result[[iv_name]]$indirect)
      mediator_names <- names(a)
      
      tibble(
        IV = iv_name,
        Mediator = mediator_names,
        a_coef = a,
        b_coef = b[mediator_names],
        weight = indirect)
    }) %>%
      mutate(effects = 'coefIndir') %>%
      mutate(depVar = dv)
    
    return(effect_df)
  }
  
  # Bootstrapping: Resample the data and apply the bootstrap_run function
  set.seed(123)  # For reproducibility
  
  bootstrap_results <- map_dfr(1:n_bootstrap, function(i) {
    
    # Resample with replacement
    resampled_data <- data[sample(nrow(data), replace = TRUE), ]
    bootstrap_run(resampled_data)
  })
  
  # Summarize the bootstrap results (e.g., by calculating means and confidence intervals)
  summary_results <- bootstrap_results %>%
    mutate(a_coef = ifelse(a_coef == 0, NA, a_coef),
           b_coef = ifelse(b_coef == 0, NA, b_coef),
           weight = ifelse(weight == 0, NA, weight)) %>%
    group_by(IV, Mediator) %>%
    summarise(
      mean_a_coef = mean(a_coef, na.rm = T),
      mean_b_coef = mean(b_coef, na.rm = T),
      mean_weight = mean(weight, na.rm = T),
      lower_ci_a_coef = quantile(a_coef, 0.025, na.rm = T),
      upper_ci_a_coef = quantile(a_coef, 0.975, na.rm = T),
      lower_ci_b_coef = quantile(b_coef, 0.025, na.rm = T),
      upper_ci_b_coef = quantile(b_coef, 0.975, na.rm = T),
      lower_ci_weight = quantile(weight, 0.025, na.rm = T),
      upper_ci_weight = quantile(weight, 0.975, na.rm = T)
    ) %>%
    mutate(depVar = dv,
           significant = ifelse(lower_ci_weight < 0 & 
                                  upper_ci_weight > 0 | 
                                  lower_ci_weight > 0 & 
                                  upper_ci_weight < 0, 
                                "Not", "Sig"))
  
  return(summary_results)
}

nb = 50
xmedOut <- xmedFunc('lag2peak_halfP', n_bootstrap = nb)

xmedOut %>%
  subset(significant == 'Sig') %>%
  ggplot(., aes(x = mean_weight, y = Mediator)) + theme_bw(base_size = 20) +
  geom_vline(xintercept = 0, linetype = 'dashed') +
  geom_linerange(aes(xmin = lower_ci_weight, xmax = upper_ci_weight, y = Mediator), #, fill = mean_a_coef, color = mean_a_coef),
                 size = 1, color = 'gray50') + 
  geom_point(aes(fill = mean_b_coef, color = mean_b_coef), 
             shape = 21, size = 6, color = 'gray50') + 
  facet_wrap(~IV) +
  #xlim(c(-.36, .36)) +
  labs(x = 'Indirect effect size', 
       fill = 'Direct effect size\nMediator -> DV', 
       color = 'Direct effect size\nMediator -> DV') +
  paletteer::scale_color_paletteer_c("grDevices::RdYlBu") +
  paletteer::scale_fill_paletteer_c("grDevices::RdYlBu") 
  #scale_size_continuous(range = c(1,8))
  
# look at all 3: a coef, b coef, weight
long_summary <- xmedOut %>%
  select(IV, Mediator, starts_with("mean_"), starts_with("lower_ci_"), starts_with("upper_ci_"), depVar) %>%
  pivot_longer(
    cols = c(mean_a_coef, mean_b_coef, mean_weight),
    names_to = "effect_type",
    names_prefix = "mean_",
    values_to = "estimate"
  ) %>%
  mutate(
    lower_ci = case_when(
      effect_type == "a_coef" ~ lower_ci_a_coef,
      effect_type == "b_coef" ~ lower_ci_b_coef,
      effect_type == "weight" ~ lower_ci_weight
    ),
    upper_ci = case_when(
      effect_type == "a_coef" ~ upper_ci_a_coef,
      effect_type == "b_coef" ~ upper_ci_b_coef,
      effect_type == "weight" ~ upper_ci_weight
    )
  )

long_summary %>%
  filter(IV == 'lag_pwd') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "2023 Lag to peak, lag PWD, all",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)

long_summary %>%
  filter(IV == 'MI60_mmhr') %>% 
  filter(!(lower_ci < 0 & upper_ci > 0)) %>%  
ggplot(., aes(x = estimate, y = fct_reorder(Mediator, estimate))) +
  geom_vline(xintercept = 0, color = "black") +
  geom_point(aes(color = effect_type), size = 3) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = effect_type), height = 0.2) +
  facet_wrap(~effect_type, scales = "free_x") +
  labs(
    x = "Effect Size with 95% CI",
    y = "Mediator",
    title = "2023 Lag to peak, MI60, all",
    color = "Effect Type"
  ) +
  theme_bw(base_size = 14)

write_csv(long_summary,
          './data/final/exploratory_mediation/2023lag2peak_bs_ridge_all.csv')



```



