---
title: "mrms spatial"
author: "Megan Sears"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

# load packages
library(here)
library(tidyverse)
library(lubridate)
library(zoo)
library(terra)
library(stars)
library(tmap)
library(sf)
library(mapview)
library(zoo)

```

# Load data

```{r}
# read in fire boundaries
et <- st_read("./data/GIS/burn_boundaries/co4020310623920201014_20200904_20210907_burn_bndy.shp")
cp <- st_read('./data/GIS/burn_boundaries/co4060910587920200813_20180915_20210907_burn_bndy.shp')

fires <- rbind(et, cp)

fires_stars <- st_as_stars(fires)

# List all the files in the directory
filenames <- list.files("/Users/megansears/Documents/MRMS/bbox_2fires/2min_2021", pattern = ".tif", full.names = TRUE)

datetime <- list.files("/Users/megansears/Documents/MRMS/bbox_2fires/2min_2021", pattern = ".tif", full.names = F)

timestamps <- substr(datetime, 12, 26)
datetime_seq <- ymd_hms(timestamps) - (7 * 60 * 60)

# Read all raster files and stack them together
stack <- read_stars(filenames, along = 3)

# Set the datetime dimension of the stack
stack_date <- st_set_dimensions(stack, 3, values = datetime_seq, names = "datetime")

# Filter the stack_date object by datetime
stack2021 <- stack_date %>%
  setNames('MI2_mmhr') %>%
  mutate(p_mm =  MI2_mmhr*(1/30)) %>%
  dplyr::select(-MI2_mmhr) %>%
  filter(datetime > ymd_hms('2021-05-31 23:58:00'),
         datetime < ymd_hms('2021-09-30 23:58:00'))

rm(stack, stack_date)

#save.image("/Users/megansears/Documents/Repos/post-fire_rainfall/bbox_2fires/stack_2023.RData")
#save.image("/Users/megansears/Documents/Repos/post-fire_rainfall/bbox_2fires/stack_2022.RData")
#save.image("/Users/megansears/Documents/Repos/post-fire_rainfall/bbox_2fires/stack_2021.RData")
load('/Users/megansears/Documents/Repos/post-fire_rainfall/bbox_2fires/stack_2023.RData')


```

# Filter

```{r}

new_crs <- st_crs(4326)

cp <- st_transform(cp, crs = new_crs)

# first filter a smaller area so I can work with it easier
stack23_crop <- st_crop(stack2023, cp)

# filter less than 0.3
filter_function <- function(x) {
  x[x < 0.3] <- 0
  return(x)
}

# filter out values less than 0.3 mm
stack2023_fil <- st_apply(
  stack23_crop,
  MARGIN = c("x", "y", "datetime"),  # dimensions
  FUN = filter_function
)


```

# Get stack into 10 mins

```{r}

# make dataset even smaller for testing
june_stack <- stack2023_fil %>%
  filter(datetime > ymd_hms('2023-05-31 23:58:00'),
         datetime < ymd_hms('2023-07-01 00:00:00'))

rm(stack2023, stack23_crop)

# make df
tibble <- as_tibble(june_stack)

rm(june_stack)
gc()

# aggregate to 10 min
stack <- tibble %>%
  mutate(datetime_round = ceiling_date(datetime, "10 mins")) %>%
  group_by(x, y, datetime_round) %>%
  rename(p_mm = filter_function) %>%
  summarize(p_mm = sum(p_mm)) %>%
  drop_na(p_mm)

rm(tibble)
gc()

###############################
# get MI60
compute_MI60 <- function(df) {
  # Calculate the rolling sum over 6 intervals (60 minutes)
  rolling_sums <- rollapply(df, width = 6, FUN = sum, na.rm = TRUE, fill = NA, align = "right")
  # Find the maximum of these rolling sums
  max(rolling_sums, na.rm = TRUE)
}


# Calculate MI60 for each pixel
stack_mi60 <- stack %>%
  group_by(x, y) %>%
  arrange(datetime_round) %>%
  mutate(MI60 = compute_MI60(p_mm)) %>%
  summarize(maxMI60 = max(MI60, na.rm = TRUE))

#testing
# tolerance <- 1e-6
# 
# stack_simple <- stack_mi60 %>%
#   filter(abs(x - -106.145) < tolerance,
#          abs(y - 40.155) < tolerance) %>%
#   filter(!p_mm == 0)

###########
stack_intens1 <- st_as_stars(stack_mi60, dims = c("x", "y"))
st_crs(stack_intens1) <- st_crs("+proj=longlat +datum=WGS84")

mapview(stack_intens1)

```

# Summer totals

```{r}

# sum summer 2023
sum_all2023 <- st_apply(
  stack2023_fil,
  MARGIN = c("x", "y"),
  FUN = sum
)

mapview(sum_all2021) + 
  mapview(fires, col.regions = NA, col = "black", alpha.regions = 0)

library(raster)

r <- as(sum_all2023, "Raster")
r_df <- as.data.frame(r, xy = TRUE)
colnames(r_df) <- c("x", "y", "value")

fire_poly <- as(fires_stars, 'Spatial')
fire_poly <- spTransform(fire_poly, CRS("+proj=longlat +datum=WGS84"))
fire_poly <- fire_poly[-2, ]
fire_poly <- fire_poly[-1, ]

fire_poly_et <- as(fires_stars, 'Spatial')
fire_poly_et <- spTransform(fire_poly_et, CRS("+proj=longlat +datum=WGS84"))
fire_poly_et <- fire_poly_et[-3, ]
fire_poly_et <- fire_poly_et[-2, ]
plot(fire_poly_et)

p2023 <- ggplot(r_df, aes(x = x, y = y, fill = value)) +
  geom_raster() +
  geom_polygon(data=fire_poly, aes(x =long, y = lat), fill = "transparent", color = "black") +
  geom_polygon(data=fire_poly_et, aes(x =long, y = lat), fill = "transparent", color = "black") +
  scale_fill_viridis_b() +
    theme_bw() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank())

p2023

ggsave("2023_total.png", plot = p2023, width = 6, height = 4, dpi = 800)

```

# Monthly sums

```{r}

# june 2023 sum
june_stack <- stack2023 %>%
  filter(datetime > ymd_hms('2023-06-01 00:00:00'),
         datetime < ymd_hms('2023-07-01 00:00:00'))

june_sum <- st_apply(
  june_stack,
  MARGIN = c("x", "y"),
  FUN = sum
)

mapview(june_sum) + 
  mapview(fires, col.regions = NA, col = "black", alpha.regions = 0)

# july 2023 sum
july_stack <- stack2023 %>%
  filter(datetime > ymd_hms('2023-07-01 00:00:00'),
         datetime < ymd_hms('2023-08-01 00:00:00'))

july_sum <- st_apply(
  july_stack,
  MARGIN = c("x", "y"),
  FUN = sum
)

mapview(july_sum) + 
  mapview(fires, col.regions = NA, col = "black", alpha.regions = 0)

# august 2023 sum
aug_stack <- stack2023 %>%
  filter(datetime > ymd_hms('2023-08-01 00:00:00'),
         datetime < ymd_hms('2023-09-01 00:00:00'))

aug_sum <- st_apply(
  aug_stack,
  MARGIN = c("x", "y"),
  FUN = sum
)

mapview(aug_sum) + 
  mapview(fires, col.regions = NA, col = "black", alpha.regions = 0)

# september 2023 sum
sept_stack <- stack2023 %>%
  filter(datetime > ymd_hms('2023-09-01 00:00:00'),
         datetime < ymd_hms('2023-10-01 00:00:00'))

sept_sum <- st_apply(
  sept_stack,
  MARGIN = c("x", "y"),
  FUN = sum
)

mapview(sept_sum) + 
  mapview(fires, col.regions = NA, col = "black", alpha.regions = 0)

rm(july_stack, june_stack, aug_stack, sept_stack)
rm(aug_sum, july_sum, june_sum, sept_sum, sum_all2023)

# counts of p>10
p10 <- stack2023 %>%
  mutate(p10 = if_else(p_mm >= 10, 1, 0)) %>%
  dplyr::select(-p_mm)


# Define a function to calculate p10
calculate_p10 <- function(x) {
  result <- ifelse(x >= 10, 1, 0)
  return(result)
}

# Apply the function to the 'p_mm' attribute
stack2023$p10 <- st_apply(stack2023, 1:2, calculate_p10)

p10 <- stack2023 %>%
  dplyr::select(-p_mm)

sum_p10 <- st_apply(
  p10,
  MARGIN = c("x", "y"),
  FUN = sum
)

mapview(sum_p10)

max_values <- st_apply(stack2023, 1:2, max)
max_values # no 2min 2023 values are greater than 10

```
