---
title: "Stage response analysis"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r, include = F}

knitr::opts_chunk$set(echo = F,
                      message = F,
                      fig.width = 12,
                      fig.height = 6)

library(tidyverse)
library(plotly)
library(here)
library(ggplot2); theme_set(theme_bw(base_size = 20,
                                     base_family = "Arial"))

```

# Read in data

```{r}

# this is only for events > 5 cm
response <- read_csv('./data/final/stage_mrms_response.csv') %>%
  mutate(across(c(datetime_peak, datetime_min, start_time.y, end_time.y), mdy_hm)) %>%
  mutate(date = mdy(date)) %>%
  mutate(site = if_else(site == 'mont',
                        'montgomery',
                        site)) %>%
  mutate(site = if_else(site == 'mich',
                        'michigan',
                        site))
  

# read in SP
sp <- read_csv('./data/final_model_inputs/sp_2000_2019_avg_catchments.csv')
elev <- read_csv('./data/final_model_inputs/elev_range.csv')
hypso <- read_csv('./data/final_model_inputs/hypso.csv')
ic <- read_csv('./data/final_model_inputs/IC_mean.csv')
inputs1 <- read_csv('./data/final_model_inputs/inputs1.csv')

inputs2 <- read_csv('./data/final_model_inputs/inputs2.csv') %>%
  distinct(site, .keep_all = T)
  
ndvi_geo <- read_csv('./data/final_model_inputs/ndvi&geo.csv') %>%
  rename(site = ID)

pwd <- read_csv('./data/final_model_inputs/pwd.csv') %>%
  mutate(date = mdy(Date)) %>%
  dplyr::select(-Date)

# join all model inputs together, except PWD b/c that's based on date
df_list <- list(elev, hypso, ic, inputs1, inputs2, ndvi_geo, sp)
inputs <- reduce(df_list, left_join, by = c("site")) %>%
  dplyr::select(-c(2:5, 9:13, 23:25, 38, 41:42)) %>%
  dplyr::select(-c(28:30, 38:43))

response <- left_join(response, pwd, by = c('site', 'date'))

all <- left_join(response, inputs, by = 'site')

```

# Stage rise

```{r}

ggplot(all, aes(x=site, y=stage_rise_cm)) +
  geom_boxplot() +
  scale_y_log10() +
  theme_bw(base_size=20)

# lag to peak
lag2p <- all %>%
  dplyr::select(site, datetime_peak, start_time.y, stage_rise_cm) %>%
  mutate(lag2peak = datetime_peak - start_time.y) %>%
  filter(!lag2peak<0)

ggplot(lag2p, aes(x=site, y=as.numeric(lag2peak))) +
  geom_boxplot() +
   scale_y_log10() +
  theme_bw(base_size=20)

all <- all %>%
  mutate(sp_cat = if_else(SP_mean > 65,
                          'high',
                          'low'))

ggplot(all, aes(x=sp_cat, y=stage_rise_cm, fill=fire)) +
  geom_boxplot() +
  #scale_y_log10() +
  theme_bw(base_size=20)


```


# Stage vs variable

```{r}

# Get column names for numeric columns from 9 to 22
numeric_cols <- names(all)[9:50]

# Create a list of plots using map
plots <- map(numeric_cols, ~{
  ggplot(all, aes(x = .data[[.x]], y = stage_rise_cm, shape = sp_cat, color=fire)) +
    geom_point(size=4,
               alpha=.7) +
    theme_bw() 
    # labs(title = paste("Boxplot for", .x), y = .x, x = "Site") +
    # theme(axis.text.x = element_text(angle = 45, hjust = 1))
})

# Print all plots
plots

```

