---
title: "East Troublesome Chem"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r, include = F}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      fig.width = 14,
                      fig.height = 6)

library(tidyverse)
library(stringr)
library(lubridate)
library(plotly)
library(kableExtra)
library(here)
library(ggplot2); theme_set(theme_bw(base_size = 24))
library(zoo)
library(corrplot)
library(stats)
library(ggcorrplot)
library(readxl)

```

# Chemistry

```{r, echo = F, warning = F}

# rmrs chem
chem <- read_csv(here('./rmrs_chem/et_waterchem.csv')) %>%
  drop_na(csu_id) %>% # drop NAs under CSU_ID
  mutate(Date = mdy(DATE)) %>%
  rename(site = csu_id) %>%
  mutate(year = year(Date))


# look at chemistry data
ggplot(chem, aes(Date, NO3, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

# look at chemistry data
ggplot(chem, aes(Date, TDN, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

# look at chemistry data
ggplot(chem, aes(Date, DOC, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

# look at chemistry data
ggplot(chem, aes(Date, NH4, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

# look at chemistry data
ggplot(chem, aes(Date, DON, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

# look at chemistry data
ggplot(chem, aes(Date, Ca, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

ggplot(chem, aes(Date, SO4, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

ggplot(chem, aes(Date, PO4, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

ggplot(chem, aes(Date, Na, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')

ggplot(chem, aes(Date, COND, color=site)) + #geom_col(position='dodge', width=15) +
  geom_point(size=4) +
  scale_x_date(date_labels="%m-%y",date_breaks  ="1 month") +
  facet_wrap(~year, scales='free_x')


```

# Predictors

```{r, include = F}
# predictors
# filter out sites that are not ET
# inputs1 <- read_csv(here('./data/final_model_inputs/inputs1.csv')) %>%
#   filter(site %in% c('p1','p2',
#                      'hum','hm',
#                      'mum','mpm',
#                      'mm_et','mub',
#                      'lum','lpm',
#                      'lm')) %>%
#   select(-c(Shape_Leng, Shape_Area, 
#             ID, area_km2))
# 
# inputs2 <- read_csv(here('./data/final_model_inputs/inputs2.csv')) %>%
#   filter(site %in% c('p1','p2',
#                      'hum','hm',
#                      'mum','mpm',
#                      'mm_et','mub',
#                      'lum','lpm',
#                      'lm')) %>%
#   select(-c(count, Shape_Leng, 
#             Shape_Area, ELONGATION, 
#             RC_CIRCLE, ID,
#             area_km2,
#             relative_area,
#             relative_elev))
# 
# inputs3 <- read_csv(here('./data/final_model_inputs/pwd.csv')) %>%
#   filter(site %in% c('p1','p2',
#                      'hum','hm',
#                      'mum','mpm',
#                      'mm_et','mub',
#                      'lum','lpm',
#                      'lm')) %>%
#   select(site, lag_pwd, Date, WY) #%>% #add this back
#   filter(Date > '2022-05-31')
# 
# inputs4 <- read_csv(here('./data/final_model_inputs/hypso.csv')) %>%
#     filter(site %in% c('p1','p2',
#                      'hum','hm',
#                      'mum','mpm',
#                      'mm_et','mub',
#                      'lum','lpm',
#                      'lm'))
# 
# # join predictor data (all except rain metrics)
# pred <- left_join(inputs2, inputs1, by = 'site')
# pred <- left_join(inputs3, pred, by = 'site')
# pred <- left_join(pred, inputs4, by = 'site')

```

# Rain

```{r, include = F}
# bring in rain predictors
# rain <- read_csv(here('./data/final/mrms/all_mrms_intensities.csv')) %>%
#   rename(site = ID) %>% 
#   filter(site %in% c('p1','p2',
#                      'hum','hm',
#                      'mum','mpm',
#                      'mm_et','mub',
#                      'lum','lpm',
#                      'lm')) %>%
#   select(-c(1, event, year)) %>%
#   mutate(Date = as.Date(start_time)) %>%
#   filter(Date > '2022-05-31')
# # how many rain dates start on the same day at the same site? *******
# #################################
# # try to join rain and chem first
# 
# 
# 
# 
# #################################
# pred <- left_join(pred, rain, by = c('site', 'Date'))
# 
# ndvi <- pred %>%
#   select(site, NDVI_2021, NDVI_2022, NDVI_2023) %>%
#   pivot_longer(!site, names_to = 'year', values_to = 'NDVI') %>%
#   mutate(year = as.numeric(sub("^NDVI_", "", year))) %>%
#   filter(!year == 2021) %>%
#   rename(WY = year)
#   
# pred <- pred %>%
#   select(-c(NDVI_2021, NDVI_2022, 
#             NDVI_2023)) %>%
#   left_join(., ndvi, by = c('site','WY'))
# 
# # lets test to make sure everything joined OK
# pred_test <- pred %>%
#   sample_n(10)
# 
# 
# 
# cor <- pred %>%
#   select(-c(site, Date,
#             start_time, end_time,
#             geology,
#             geo_general))
# 
# 
# matrix_cor_pred <- cor(cor, use = 'complete.obs')
# 
# ggcorrplot(matrix_cor_pred,
#            lab = T)
# 
# ```
# 
# # Chem with predictors
# 
# ```{r, include = F}
# 
# all <- left_join(chem, pred, by = c('site', 'Date'))
# 
# # prep for cor matrix
# chem_cor <- all %>%
#   select(-c(site, Date, geology, geo_general, start_time, end_time))
# 
# predictor_names <- names(chem_cor)[1:31]
# response_names <- names(chem_cor)[38:50]
# 
# correlation_matrix <- cor(chem_cor[c(response_names, predictor_names)],
#                           use = 'complete.obs')
# 
# 
# 
# ggcorrplot(correlation_matrix,
#            lab = T)
# 
# ggplot(chem_cor, aes(catchment_area_km2, TSS)) + geom_point()

```


