---
title: "pull PRISM 800m"
author: "Megan Sears"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

library(tidyverse)
library(httr)
library(terra)

```

# Function to pull PRISM 800m

```{r}

get_prism800 <- function(url, outdir) {
  
  fname_date <- gsub(".*/", "", url) # date from URL
  var <- "ppt" # ppt # tmean
  region <- "us" # CONUS
  res <- "800m" # 800 m 
  
  # File paths
  fname_base <- paste(var, 
                      region, 
                      res, 
                      fname_date, 
                      sep = "_")
  
  zipfile <- file.path(outdir, 
                       paste0(fname_base, 
                              ".zip"))
  
  unzipdir <- file.path(outdir, 
                        paste0(fname_base, 
                               "_unzipped"))
  
  # Download ZIP
  resp <- GET(url, write_disk(zipfile, 
                              overwrite = TRUE), 
              progress())
  
  if (http_error(resp)) stop("Download failed: ", url)
  
  # Unzip
  unzip(zipfile, exdir = unzipdir)
  
  # Find the raster inside the ZIP (.tif)
  raster_file <- list.files(unzipdir, pattern = "\\.tif$", full.names = TRUE)[1]
  if (is.na(raster_file)) stop("No raster found in ZIP for ", fname_date)
  
  # Read raster
  rast(raster_file)
}

```


```{r}

# This is mrms summer 23 data
# Used for crs and extent later on
sum_all23 <- rast('/Volumes/MSears_Mac2/Documents/MRMS/mrms_data/bbox_2fires/summertotal_2023_fil01.tif')

# Folder to save downloads
outdir <- "/Volumes/MSears_Mac2/Documents/PRISM800_pixel/p23"

# Date range for function
dates_tbl <- tibble(
  date = seq(ymd("2023-06-01"), 
             ymd("2023-09-30"), 
             by = "day")) %>%
  mutate(date_str = format(date, 
                           "%Y%m%d"),
    url = paste0("https://services.nacse.org/prism/data/get/us/800m/ppt/", # "https://services.nacse.org/prism/data/get/us/800m/ppt/"
                 date_str))

# Run the function w/ urls
rasters <- dates_tbl %>%
  pull(url) %>%
  map(~ get_prism800(.x, outdir))

# Stack into a single SpatRaster
P_prism_stack <- rast(rasters)

# # Sum for JJAS total - this is CONUS
# prismSum <- sum(P_prism_stack, 
#                 na.rm = TRUE)

# Project  
prism_proj <- project(P_prism_stack,
                      "EPSG:4326") # matches sum_all23

# Crop to mrms summer total for figure
prismJJAS23 <- crop(prism_proj,
                    sum_all23)

#plot(prismJJAS21)

writeRaster(prismJJAS23,
            '/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_ppt_JJAS2023.tif')

```

# Catchment air T

```{r}

all_sites <- vect('/Users/megansears/Library/CloudStorage/OneDrive-Colostate/PhD/post-fire_rain_response/data/GIS/catchments_all/catchments_all_lidar.shp')
all_sites$site[all_sites$site == "mm"] <- "mm_et"

plot(all_sites)

tmin21 <- prismJJAS21 %>%
  terra::extract(all_sites, fun = mean) %>%
  mutate(site = all_sites$site)

tmin21_long <- tmin21 %>%
  pivot_longer(-c(site,ID),
               names_to = 'dates',
               values_to = 'tmin')

write_csv(tmin23_long,
          '/Users/megansears/Documents/PRISM800/tmin23_catchments.csv')

```

# Days with tmean < 3°C and precip > 0

```{r}

years <- c(2021, 2022, 2023)

snow_days <- map(years, \(yr) {

  tmean <- rast(str_glue('/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_tmean_JJAS{yr}.tif'))
  ppt   <- rast(str_glue('/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_ppt_JJAS{yr}.tif'))

  # pixels where both conditions met on the same day
  both <- (tmean < 3) & (ppt > 0)

  total_pixels <- global(!is.na(tmean[[1]]), fun = "sum", na.rm = TRUE)[[1]]

  ppt_masked <- mask(ppt, both, maskvalues = 0)

  n_df   <- global(both,       fun = "sum", na.rm = TRUE)
  min_df <- global(ppt_masked, fun = "min", na.rm = TRUE)
  max_df <- global(ppt_masked, fun = "max", na.rm = TRUE)

  n_df %>%
    mutate(
      date         = as.Date(names(tmean), format = "prism_tmean_us_30s_%Y%m%d"),
      year         = yr,
      total_pixels = total_pixels,
      ppt_min      = min_df$min,
      ppt_max      = max_df$max
    )

}) %>%
  list_rbind() %>%
  rename(n_pixels = sum) %>%
  mutate(pct_pixels = round(n_pixels / total_pixels * 100, 2)) %>%
  select(date, year, n_pixels, pct_pixels, ppt_min, ppt_max) %>%
  filter(n_pixels > 0)

###########

# verify: 2021-06-01 should have 1266 pixels (6.54%) meeting both conditions
tmean_v <- rast('/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_tmean_JJAS2021.tif')
ppt_v   <- rast('/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_ppt_JJAS2021.tif')

# first layer = 2021-06-01
tmean_day <- tmean_v[[1]]
ppt_day   <- ppt_v[[1]]

n_cold     <- global(tmean_day < 3,              fun = "sum", na.rm = TRUE)[[1]]
n_wet      <- global(ppt_day > 0,               fun = "sum", na.rm = TRUE)[[1]]
n_both     <- global((tmean_day < 3) & (ppt_day > 0), fun = "sum", na.rm = TRUE)[[1]]
total_px   <- global(!is.na(tmean_day),          fun = "sum", na.rm = TRUE)[[1]]

message("2021-06-01 verification:")
message("  tmean < 3 only:      ", n_cold, " pixels (", round(n_cold / total_px * 100, 2), "%)")
message("  ppt > 0 only:        ", n_wet,  " pixels (", round(n_wet  / total_px * 100, 2), "%)")
message("  both (expected 1266):", n_both, " pixels (", round(n_both / total_px * 100, 2), "%)")

stopifnot(n_both == 1266)
message("Verification passed.")

```


```{r}

snow_days <- map(years, \(yr) {

  tmean <- rast(str_glue('/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_tmean_JJAS{yr}.tif'))
  ppt   <- rast(str_glue('/Volumes/MSears_Mac2/Documents/PRISM800_pixel/prism800m_ppt_JJAS{yr}.tif'))

  both <- (tmean < 3) & (ppt > 0)

  # mask ppt to only pixels meeting both conditions
  ppt_masked <- mask(ppt, both, maskvalues = 0)

  total_pixels <- global(!is.na(tmean[[1]]), fun = "sum", na.rm = TRUE)[[1]]

  n_df   <- global(both,       fun = "sum", na.rm = TRUE)
  min_df <- global(ppt_masked, fun = "min", na.rm = TRUE)
  max_df <- global(ppt_masked, fun = "max", na.rm = TRUE)

  n_df %>%
    mutate(
      date         = as.Date(names(tmean), format = "prism_tmean_us_30s_%Y%m%d"),
      year         = yr,
      total_pixels = total_pixels,
      ppt_min      = min_df$min,
      ppt_max      = max_df$max
    )

}) %>%
  list_rbind() %>%
  rename(n_pixels = sum) %>%
  mutate(pct_pixels = round(n_pixels / total_pixels * 100, 2)) %>%
  select(date, year, n_pixels, pct_pixels, ppt_min, ppt_max) %>%
  filter(n_pixels > 0)

snow_days %>%
  select(-year) %>%
  mutate(
    ppt_min = round(ppt_min, 2),
    ppt_max = round(ppt_max, 2)
  ) %>%
  knitr::kable(
    col.names = c("Date",
                  "Number of pixels with mean air temperature <3 deg C and precipitation > 0 mm",
                  "Percent of total pixels",
                  "Min precip (mm)",
                  "Max precip (mm)"),
    align = c("l", "r", "r", "r", "r")
  )

```

