---
title: "Post-fire stream response"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(viridis)

# Set a basic ggplot theme
theme_set(theme_bw(base_size = 20))

```

```{r}

response <- read_csv('./data/final_model_inputs/events_inputs_v2.csv') %>%
  select(site,
         sp_cat, # categorical
         fire, # categorical
         stage_rise_cm,
         lag2peak_halfP,
         lag2peak_Pstart,
         MI60_mmhr,
         lag_pwd,
         terrain_hypso75 = hypso75,
         terrain_hypso25 = hypso25,
         terrain_hypso50 = hypso50,
         terrain_connec = IC,
         terrain_conn_dnbr = hydraulic_func_conn,
         area_km2 = area_km2.x,
         terrain_rc_circle = RC_CIRCLE.x,
         terrain_slope40 = slope40_frac,
         soil_brockdepmin = brockdepmin,
         terrain_recharge = frac_recharge_area,
         #terrain_vbw = avg_vbw_m,
         soil_sand = AVG_SAND,
         mean_dnbr, 
         soil_clay = AVG_CLAY,
         soil_ksat = AVG_KSAT, 
         terrain_elongation = ELONGATION.x, 
         soil_availwaterstor = aws0150wta, 
         NDVI, 
         terrain_vall_holl = frac_valley,
         terrain_flowlength = flow_length_m, 
         terrain_slope30 = slope30_frac, 
         SP_mean,
         terrain_hypsoint = hypso_integral,
         year,
         terrain_glacial = frac_glacial,
         fire_no,
         mulch_frac) %>%
  mutate(site_number = as.integer(factor(site))) %>% # give each site a number
  select(-site)
  
  connec <- response %>%
    select(site, IC) %>%
    distinct(site, .keep_all = T)

```

# MI60 vs stage rise

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width=10, fig.height=6}

vars <- c('terrain_connec',
          'terrain_slope30',
          'terrain_hypso75',
          'terrain_elongation',
          'terrain_recharge',
          'mean_dnbr',
          'SP_mean',
          'terrain_glacial',
          'terrain_vall_holl',
          'soil_clay',
          'terrain_flowlength',
          'soil_ksat'
)

# plot for each var
plot_var_color <- function(var_name) {
  ggplot(response, aes(x = MI60_mmhr, 
                       y = stage_rise_cm, 
                       color = .data[[var_name]],
                       shape=fire)) +
    geom_point(size = 3, alpha = 0.8) +
    scale_color_viridis(option = "D", direction = -1, name = var_name,
                        guide = guide_colorbar(barwidth = 1.5, barheight = 10))
}

# Apply the function to each variable and return a list of plots
stage_plots <- map(vars, plot_var_color)

stage_plots

```

# MI60 vs stage rise by fire

```{r}

# plot for each var
plot_var_color <- function(var_name) {
  ggplot(response, aes(x = MI60_mmhr, 
                       y = stage_rise_cm, 
                       color = .data[[var_name]])) +
    geom_point(size = 3, alpha = 0.8) +
    scale_color_viridis(option = "D", direction = -1, name = var_name,
                        guide = guide_colorbar(barwidth = 1.5, barheight = 10)) +
    facet_wrap(~fire)
}

# Apply the function to each variable and return a list of plots
stage_plots <- map(vars, plot_var_color)

stage_plots

```

# MI60 vs stage rise by SZ

```{r}

# plot for each var
plot_var_color <- function(var_name) {
  # ggplot(response, aes(x = MI60_mmhr, 
  #                      y = stage_rise_cm, 
  #                      color = .data[[var_name]],
  #                      shape=fire)) +
  #   geom_point(size = 3, alpha = 0.8) +
  #   scale_color_viridis(option = "D", direction = -1, name = var_name,
  #                       guide = guide_colorbar(barwidth = 1.5, barheight = 10)) +
  #   facet_wrap(~sp_cat)
  
quintile_labels <- c("Very Low", "Low", "Medium", "High", "Very High")

  response %>%
    mutate(color_group = ntile(.data[[var_name]], 5),
           color_group = factor(color_group,
                                levels = 1:5,
                                labels = quintile_labels)) %>%
    ggplot(aes(x = MI60_mmhr,
               y = stage_rise_cm,
               color = color_group,
               shape = fire)) +
    geom_point(size = 5, alpha = 0.65) +
    geom_smooth(method = "lm", se = FALSE, linewidth = 1.2) + 
    scale_color_viridis_d(option = "viridis",
                          name = paste0(var_name, " (quintiles)")) +
    facet_wrap(~sp_cat)
}

plot_var_color <- function(var_name) {
  tertile_labels <- c("Low", "Medium", "High")

  response %>%
    mutate(color_group = ntile(.data[[var_name]], 3),
           color_group = factor(color_group,
                                levels = 1:3,
                                labels = tertile_labels)) %>%
    ggplot(aes(x = MI60_mmhr,
               y = stage_rise_cm)) +
    geom_point(aes(color = color_group, shape=sp_cat), size = 5, alpha = 0.65) +
    #geom_smooth(aes(color = color_group, fill = color_group), 
    #            method = "lm", se = TRUE, linewidth = 1.2, alpha = 0.2) +
    scale_color_viridis_d(option = "viridis",
                          name = paste0(var_name, " (tertiles)")) +
    #cale_fill_viridis_d(option = "viridis", guide = "none") +  # hide duplicate fill legend
    facet_wrap(~fire )
}

# Apply the function to each variable and return a list of plots
stage_plots <- map(vars, plot_var_color)

stage_plots

```

# MI60 vs lag to peak

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width=10, fig.height=6}

# plot for each var
plot_var_color <- function(var_name) {
  ggplot(response, aes(x = MI60_mmhr, 
                       y = lag2peak_halfP, 
                       color = .data[[var_name]],
                       shape=fire)) +
    geom_point(size = 3, alpha = 0.8) +
    scale_color_viridis(option = "D", direction = -1, name = var_name,
                        guide = guide_colorbar(barwidth = 1.5, barheight = 10))
}

# Apply the function to each variable and return a list of plots
lag_plots <- map(vars, plot_var_color)

lag_plots

```

# MI60 vs lag to peak by fire

```{r}

# plot for each var
plot_var_color <- function(var_name) {
  ggplot(response, aes(x = MI60_mmhr, 
                       y = lag2peak_halfP, 
                       color = .data[[var_name]])) +
    geom_point(size = 3, alpha = 0.8) +
    scale_color_viridis(option = "D", direction = -1, name = var_name,
                        guide = guide_colorbar(barwidth = 1.5, barheight = 10)) +
    facet_wrap(~fire)
}

# Apply the function to each variable and return a list of plots
lag_plots <- map(vars, plot_var_color)

lag_plots

```

# MI60 vs lag to peak by SZ

```{r}

# plot for each var
plot_var_color <- function(var_name) {
  ggplot(response, aes(x = MI60_mmhr, 
                       y = lag2peak_halfP, 
                       color = .data[[var_name]],
                       shape=fire)) +
    geom_point(size = 3, alpha = 0.8) +
    scale_color_viridis(option = "D", direction = -1, name = var_name,
                        guide = guide_colorbar(barwidth = 1.5, barheight = 10)) +
    facet_wrap(~sp_cat)
}

# Apply the function to each variable and return a list of plots
lag_plots <- map(vars, plot_var_color)

lag_plots

```

